package handlers

import (
	"github.com/gofiber/fiber/v2"
)

func GetReport(c *fiber.Ctx) error {
	buildingID := c.Params("building_id")
	if buildingID == "" {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": "Building ID is required",
		})
	}

	return c.JSON(fiber.Map{
		"incidents": []any{},
		"inquiries": []fiber.Map{
			{
				"id":               145339,
				"documentName":     "Dossiernummer 1966-7049 Schiedam.pdf",
				"inspection":       false,
				"jointMeasurement": false,
				"floorMeasurement": false,
				"note":             nil,
				"documentDate":     "1966-11-21T00:00:00",
				"documentFile":     "39eb036b-5a41-498c-83b3-5937873a99e8.pdf",
				"type":             7,
				"standardF3o":      false,
				"attribution": fiber.Map{
					"id":             0,
					"reviewer":       "6c6b646e-3ad7-4373-9f79-c061abe2ab48",
					"reviewerName":   "schiedam@kcaf.nl",
					"creator":        "9fa1b0a9-4b04-4cdd-94e7-66fa5ee187ad",
					"creatorName":    "don@schiedam.nl",
					"owner":          "7ecb4f7a-75ce-4b2f-b9c2-68ddd502a5ae",
					"ownerName":      "Gemeente Schiedam",
					"contractor":     10,
					"contractorName": "FunderMaps B.V.",
				},
				"state": fiber.Map{
					"auditStatus": 4,
					"allowWrite":  false,
				},
				"access": fiber.Map{
					"accessPolicy": 1,
					"isPublic":     false,
					"isPrivate":    true,
				},
				"record": fiber.Map{
					"createDate": "2025-02-10T10:43:12.520961Z",
					"updateDate": "2025-02-10T10:44:48.067023Z",
					"deleteDate": nil,
				},
			},
		},
		"inquirySamples": []fiber.Map{
			{
				"id":                              885984,
				"inquiry":                         145339,
				"address":                         "gfm-cadf91ef0bfe4b509ba57d6293317140",
				"building":                        nil,
				"note":                            nil,
				"builtYear":                       "1966-01-31T00:00:00",
				"substructure":                    nil,
				"cpt":                             nil,
				"monitoringWell":                  nil,
				"groundwaterLevelTemp":            nil,
				"groundLevel":                     nil,
				"groundwaterLevelNet":             nil,
				"foundationType":                  10,
				"enforcementTerm":                 nil,
				"recoveryAdvised":                 nil,
				"damageCause":                     nil,
				"damageCharacteristics":           nil,
				"constructionPile":                nil,
				"woodType":                        nil,
				"woodEncroachement":               nil,
				"constructionLevel":               nil,
				"woodLevel":                       nil,
				"pileDiameterTop":                 nil,
				"pileDiameterBottom":              nil,
				"pileHeadLevel":                   nil,
				"pileTipLevel":                    nil,
				"foundationDepth":                 nil,
				"masonLevel":                      nil,
				"concreteChargerLength":           nil,
				"pileDistanceLength":              nil,
				"woodPenetrationDepth":            nil,
				"overallQuality":                  nil,
				"woodQuality":                     nil,
				"constructionQuality":             nil,
				"woodCapacityHorizontalQuality":   nil,
				"pileWoodCapacityVerticalQuality": nil,
				"carryingCapacityQuality":         nil,
				"masonQuality":                    nil,
				"woodQualityNecessity":            nil,
				"crackIndoorRestored":             nil,
				"crackIndoorType":                 nil,
				"crackIndoorSize":                 nil,
				"crackFacadeFrontRestored":        nil,
				"crackFacadeFrontType":            nil,
				"crackFacadeFrontSize":            nil,
				"crackFacadeBackRestored":         nil,
				"crackFacadeBackType":             nil,
				"crackFacadeBackSize":             nil,
				"crackFacadeLeftRestored":         nil,
				"crackFacadeLeftType":             nil,
				"crackFacadeLeftSize":             nil,
				"crackFacadeRightRestored":        nil,
				"crackFacadeRightType":            nil,
				"crackFacadeRightSize":            nil,
				"deformedFacade":                  nil,
				"thresholdUpdownSkewed":           nil,
				"thresholdFrontLevel":             nil,
				"thresholdBackLevel":              nil,
				"skewedParallel":                  nil,
				"skewedParallelFacade":            nil,
				"skewedPerpendicular":             nil,
				"skewedPerpendicularFacade":       nil,
				"settlementSpeed":                 nil,
				"skewedWindowFrame":               nil,
				"facadeScanRisk":                  nil,
				"createDate":                      "2025-02-10T10:44:46.087386Z",
				"updateDate":                      nil,
				"deleteDate":                      nil,
			},
		},
		"recoveries":      []any{},
		"recoverySamples": []any{},
	})
}
